spring:
  application:
    name : order-service
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: order_topics

  # Kafka producer configuration
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
